name: Release driver

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate archive
        run: |
          sed -e "s/@PKGVER@/$(git tag --points-at HEAD)/" -i dkms.conf
          tar -czf driver.tar.gz Makefile aorus-laptop.c dkms.conf
      - name: Get checksum
        run: sha256sum driver.tar.gz | tee sum.txt
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
            sum.txt
            driver.tar.gz
  
  generate-rpm:
    name: Generate RPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate RPM package
        id: rpmbuild
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: pkg-files/aorus-laptop-kmod.spec
      - name: Upload RPM package
        uses: actions/upload-artifact@v4
        with:
          name: aorus-laptop-kmod
          path: ${{ steps.rpmbuild.outputs.rpm_dir_path }}