name: Test RPM
on: push

jobs:

  generate-rpm:
    name: Generate RPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate RPM package
        id: rpmbuild
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: pkg-files/aorus-laptop-kmod.spec
          additional_repos: "['fedora-40', 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm']"
      - name: Upload RPM package
        uses: actions/upload-artifact@v4
        with:
          name: aorus-laptop-kmod
          path: ${{ steps.rpmbuild.outputs.rpm_dir_path }}